# Generated by Django 4.2.6 on 2023-10-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=2048, verbose_name='wallet')),
                ('usd', models.FloatField(verbose_name='usd')),
                ('rdw', models.FloatField(verbose_name='rdw')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
    ]
