# Generated by Django 4.2.6 on 2023-10-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanging', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
